/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JA_FitDialog.java
 *
 * Created on 25.02.2010, 14:37:00
 */

package janalyzer;

import java.text.*;
import javax.swing.*;
import javax.swing.text.*;

/**
 *
 * @author cpieper
 */
public class JA_BaselineDlg extends javax.swing.JDialog {

    public static final int ID_OK = 0;
    public static final int ID_CANCEL = 99;
    
    private int retval;
    private JA_Main parent = null;

    /** Creates new form JA_FitDialog */
    public JA_BaselineDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        if (parent instanceof JA_Main)
            this.parent = (JA_Main)parent;
        retval = -1;
        initComponents();
        setLocationRelativeTo(null);

        DecimalFormat df;
        NumberFormatter nf;
        MaskFormatter mf;

        df = new DecimalFormat();
        df.setMaximumIntegerDigits(3);
        df.setMaximumFractionDigits(3);
        df.setGroupingUsed(false);
        nf = new NumberFormatter(df);
        nf.setValueClass(Double.class);
        nf.setMinimum(new Double(0));
        nf.setMaximum(new Double(100));


        jFormattedTextField_Range1.setFormatterFactory(new DefaultFormatterFactory(nf));
        jFormattedTextField_Range2.setFormatterFactory(new DefaultFormatterFactory(nf));

        jFormattedTextField_Range1.setValue(new Double(4));
        jFormattedTextField_Range2.setValue(new Double(20));
    }

    public void setBaseBinning(double res_ps) {
        DefaultComboBoxModel cm = new DefaultComboBoxModel();
        for (int i = 0; i < 6; i++) {
            int fac = (1 << i);
            double nb = fac * res_ps;
            cm.addElement(new Binning(nb, fac));
        }
        jComboBox_NewRes.setModel(cm);
    }

    public int getRebinFactor() {
        if (jCheckBox_ReBin.isSelected()) {
            Object o = jComboBox_NewRes.getSelectedItem();
            if ((o != null) && (o instanceof Binning)) {
                return ((Binning)o).getFactor();
            }
        }
        return 1;
    }

    public boolean doBaseline() {
        return jCheckBox_Baseline.isSelected();
    }

    public double[] getRange() {
        double[] lt;
        lt = new double[2];
        lt[0] = (Double)jFormattedTextField_Range1.getValue();
        lt[1] = (Double)jFormattedTextField_Range2.getValue();
        return lt;
    }

    public void setRange(double r1, double r2) {
        jFormattedTextField_Range1.setValue(new Double(r1));
        jFormattedTextField_Range2.setValue(new Double(r2));
    }

    public class Range {
        public double start, stop;

        Range(double start, double stop) {
            this.start = start;
            this.stop = stop;
        }
    }

    public class Binning extends Object {
        private double bin_ps;
        private int factor;

        Binning(double bin_ps, int factor) {
            this.bin_ps = bin_ps;
            this.factor = factor;
        }

        @Override
        public String toString() {
            return bin_ps + " ps";
        }

        /**
         * @return the bin_ns
         */
        public double getBin_ps() {
            return bin_ps;
        }

        /**
         * @param bin_ns the bin_ns to set
         */
        public void setBin_ps(double bin_ps) {
            this.bin_ps = bin_ps;
        }

        /**
         * @return the factor
         */
        public int getFactor() {
            return factor;
        }

        /**
         * @param factor the factor to set
         */
        public void setFactor(int factor) {
            this.factor = factor;
        }
    }

    public int getReturnVal() {
        return retval;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_NewRes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField_Range1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField_Range2 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton_CANCEL = new javax.swing.JButton();
        jButton_OK = new javax.swing.JButton();
        jCheckBox_Baseline = new javax.swing.JCheckBox();
        jCheckBox_ReBin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baseline/ Rebin");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jComboBox_NewRes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Curve 1", "Curve 2" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("New Resolution:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Baseline:");

        jFormattedTextField_Range1.setText("1");
        jFormattedTextField_Range1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField_Range1PropertyChange(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("ns  to");

        jFormattedTextField_Range2.setText("12");
        jFormattedTextField_Range2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField_Range2PropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("ns");

        jButton_CANCEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_CANCEL.setText("Cancel");
        jButton_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CANCELActionPerformed(evt);
            }
        });

        jButton_OK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_OK.setText("OK");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jCheckBox_Baseline.setText("Subtract baseline");
        jCheckBox_Baseline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BaselineActionPerformed(evt);
            }
        });

        jCheckBox_ReBin.setText("Change TCSPC bining");
        jCheckBox_ReBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ReBinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_ReBin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_NewRes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_Baseline)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_CANCEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_Range1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_Range2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_ReBin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_NewRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jCheckBox_Baseline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField_Range1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField_Range2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CANCEL)
                    .addComponent(jButton_OK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CANCELActionPerformed
        retval = ID_CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_jButton_CANCELActionPerformed

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        retval = ID_OK;
        this.setVisible(false);
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*setLocationRelativeTo(null);
        Object val1 = jFormattedTextField_Range1.getValue();
        Object val2 = jFormattedTextField_Range2.getValue();
        parent.updateCursor(((Double)val1).doubleValue(), ((Double)val2).doubleValue());

        jCheckBox_ReBin.setSelected(false);
        jCheckBox_Baseline.setSelected(false);
        jComboBox_NewRes.setEnabled(false);
        jFormattedTextField_Range1.setEnabled(false);
        jFormattedTextField_Range2.setEnabled(false);*/
    }//GEN-LAST:event_formWindowOpened

    private void jFormattedTextField_Range1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField_Range1PropertyChange
        Object val1 = jFormattedTextField_Range1.getValue();
        Object val2 = jFormattedTextField_Range2.getValue();
        if ((parent != null) && (val1 instanceof Double) && (val2 instanceof Double))
            parent.updateCursor(((Double)val1).doubleValue(), ((Double)val2).doubleValue());
    }//GEN-LAST:event_jFormattedTextField_Range1PropertyChange

    private void jFormattedTextField_Range2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField_Range2PropertyChange
        Object val1 = jFormattedTextField_Range1.getValue();
        Object val2 = jFormattedTextField_Range2.getValue();
        if ((parent != null) && (val1 instanceof Double) && (val2 instanceof Double))
            parent.updateCursor(((Double)val1).doubleValue(), ((Double)val2).doubleValue());
    }//GEN-LAST:event_jFormattedTextField_Range2PropertyChange

    private void jCheckBox_BaselineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BaselineActionPerformed
        jFormattedTextField_Range1.setEnabled(jCheckBox_Baseline.isSelected());
        jFormattedTextField_Range2.setEnabled(jCheckBox_Baseline.isSelected());
    }//GEN-LAST:event_jCheckBox_BaselineActionPerformed

    private void jCheckBox_ReBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ReBinActionPerformed
        jComboBox_NewRes.setEnabled(jCheckBox_ReBin.isSelected());
    }//GEN-LAST:event_jCheckBox_ReBinActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(parent);
        retval = ID_CANCEL;
        Object val1 = jFormattedTextField_Range1.getValue();
        Object val2 = jFormattedTextField_Range2.getValue();
        parent.updateCursor(((Double)val1).doubleValue(), ((Double)val2).doubleValue());

        jCheckBox_ReBin.setSelected(false);
        jCheckBox_Baseline.setSelected(false);
        jComboBox_NewRes.setEnabled(false);
        jFormattedTextField_Range1.setEnabled(false);
        jFormattedTextField_Range2.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JA_BaselineDlg dialog = new JA_BaselineDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CANCEL;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JCheckBox jCheckBox_Baseline;
    private javax.swing.JCheckBox jCheckBox_ReBin;
    private javax.swing.JComboBox jComboBox_NewRes;
    private javax.swing.JFormattedTextField jFormattedTextField_Range1;
    private javax.swing.JFormattedTextField jFormattedTextField_Range2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}
